export const FETCH_LOCATIONS_BY_QUERY = 'FETCH_LOCATIONS_BY_QUERY';
export const GET_CURRENT_LOCATION_WEATHER_CONDITION = 'GET_CURRENT_LOCATION_WEATHER_CONDITION';
export const GET_TODAYS_HIGH_AND_LOW_TEMPERATURES = 'GET_TODAYS_HIGH_AND_LOW_TEMPERATURES';
export const FETCH_HOURLY_FORECASTS_FOR_NEXT_24_HOURS = 'FETCH_HOURLY_FORECASTS_FOR_NEXT_24_HOURS';
export const FETCH_FORECAST_FOR_NEXT_10_DAYS = 'FETCH_FORECAST_FOR_NEXT_10_DAYS';